### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by AngelTiramisu** [t2pellet/strawgolem#110] opened 2022-10-19 19:19 UTC
**Game Info**
Game Version : 1.18.2 
Mod Version : 1.18.2-2.0.0
Mod Loader : Forge

**Describe the bug**
The StrawGolem is trying to access the Waystone Plate Inventory and that crashes the server 

**Screenshots**

**Additional context**
[crash-2022-10-19_14.21.15-server.txt](https://github.com/t2pellet/strawgolem/files/9823571/crash-2022-10-19_14.21.15-server.txt)

**Comment by t2pellet** [comment] 2022-12-05 16:08
duplicate of https://github.com/t2pellet/strawgolem/issues/109

**Closed by t2pellet** 2022-12-05 16:08 UTC
Labels: wip
