### ISSUE TITLE
1.19.2 beta crash

### ISSUE THREAD

**Issue by GoobyMain** [t2pellet/strawgolem#111] opened 2022-11-09 22:29 UTC
**Game Info**
Game Version : 1.19.2
Mod Version : forge-1.19-2.0.0b2
Mod Loader : forge

**Describe the bug**
The game doesn't launch with the mod in the forge "mods" folder, restarting the launcher gives a game crashed error with exit code 1, and the crash leaves no crash report

![image](https://user-images.githubusercontent.com/103806308/200955890-b22e4935-d846-4285-a2ef-440ed77dd71c.png)

**Comment by GoobyMain** [comment] 2022-11-09 22:32
it crashes like this even as the only mod loaded, so it's not a compatibility issue

**Comment by t2pellet** [comment] 2022-12-05 15:53
duplicate of https://github.com/t2pellet/strawgolem/issues/107

**Closed by t2pellet** 2022-12-05 15:53 UTC
