### ISSUE TITLE
Various Errors

### ISSUE THREAD

**Issue by ArturilloD** [t2pellet/strawgolem#9] opened 2020-08-11 12:07 UTC
It has three problems, one is that it does not detect the closest chest, it stays on the wall looking towards another more distant chest, even with the vertical minimum (2) it detects chests more than 2 blocks away.

The other that I do not know if it is intentional, is that it does not release seeds, for example with wheat it never obtains seeds, as with other modifications such as Mystical Agriculture, it never obtains seeds.

And last but not least, although there is no space in the chest, they continue to put elements, now, I have not proven what happens with different elements.

**Comment by daPoseidonGuy** [comment] 2020-08-16 14:37
For distant chests, look to the horizontal minimum option. If you want it to detect a specific chest in the newer versions you can designate a priority chest by shift right clicking the golem and then a chest with some wheat

No seeds is the current design

The last is a duplicate of this https://github.com/daPoseidonGuy/strawgolem/issues/8

**Comment by ArturilloD** [comment] 2020-08-16 17:53
Wow sorry I did not realize. It always detects the chest when I make the
golem spawn when some crop is ripe and spawn it on top.
By the way, golems stop harvesting when they are on a farm with more than
one story. Greetings and thanks.

**Comment by daPoseidonGuy** [comment] 2020-08-17 16:17
No worries :)

If its more than one story, have you tried increasing the vertical search range so they can find them?

**Comment by ArturilloD** [comment] 2020-08-17 18:38
Yes, I have set it the minimum to try not to detect the bottom one, because
it is always the bottom one and you have to make a minimum height of two
between the chest and the chest so that they do not stop it. I have also
detected that golems do not collect flowers well from: "
https://www.curseforge.com/minecraft/mc-mods/finally-farmable-dyes"

**Comment by daPoseidonGuy** [comment] 2020-08-26 14:16
Golems need to be able to see the crop in order to harvest it by design. That is likely the issue here.

If you have a multiple story farm, best is to have golems on each floor

Ensure your vertical search range is large enough. It needs ot be greater than the vertical distance (in blocks) between the golem and the crops you want it to see.

As for the mod compat request, I've added it to the list.

**Comment by ArturilloD** [comment] 2020-08-26 14:44
Well thank you, the golems do see the crops and if there are golems in each
plant, the point is that I don't know very well because they look down, as
if the golems below gave them some instruction, heh.

Another thing that I think would be interesting would be to be able to make
the golems be able to pick up items from the ground, that is, those items
that remain floating on the ground.

I esque I have two mods installed that look alike, the strawGolem and the
agriAnimal, the agriAnimal is like a fox, although not really, since it
dies with the berries, hehe. The point is that this "fox" can collect items
from the ground and is also capable of collecting seeds and planting them,
when he has no space to plant them, he keeps them in his inventory of 8
slots, when the inventory is full then loose in some nearby inventory. It
is a bit of a hassle to wait for the inventory to fill up, plus you can
only plant and collect from normal farmland, but the good thing about
strawgolems is that they can do it in different ones like
mysticalAgriculture or farmingForBlockHeads. Incredible that detail really,
since it allows a larger range of play.

On the other hand I wanted to notify you that the straw golems when there
is a pipe on top of the chest or storage entity if they leave the items,
although if there is a pipe like the prettyPipes for example sometimes they
stay jumping there and do not move for a while, just They jump, as if they
were stuck and another thing that happens is that when there is a block
above the storage entity, the strawGolems do not enter items even though
that entity exists, that is, if you place a chest and you can open then
they enter items, on the other hand if you cannot open it because there is
a block above then they do not enter anything, now, I think that rule of 3
does not hold with the stairs, now when I can I will do a test and I will
notify you, I think that even if there is a ladder on top, no elements
enter either.

Greetings and thanks for everything, congratulations on the great mod. I do
not know if you plan to do something else, that is, give strawGolems or
other capabilities, I say this because I have several ideas and if you are
interested, tell me that I will tell you. Hopefully soon learn to program
in Java, this way I could help and create those things that I have in my
head, hehe. Regards

**Closed** 2020-11-04 01:30 UTC
