### ISSUE TITLE
Straw golem should only pickup pumpkins and melons that are connected to a stem

### ISSUE THREAD

**Issue by kihgy** [t2pellet/strawgolem#24] opened 2021-02-19 11:16 UTC
If you look carefully, you can see that even if you place down a pumpkin next to a stem, the stem wont connect, only those that produced by the stem does, same goes for melon, so my request is to have the golem to only harvest the blocks when it is connected to the stem lol.

**Comment by kihgy** [comment] 2021-02-19 11:35
Would hate it to have the golem destroy my decorative pumpkin garden.

**Comment by t2pellet** [comment] 2021-03-06 15:34
Done!

Attached the fixed version - it will be included in the next release as well. Feel free to comment here again if you find the issue is still occuring
[fix.zip](https://github.com/t2pellet/strawgolem/files/6095600/fix.zip)

**Closed** 2021-03-06 15:34 UTC

**Comment by ejm554** [comment] 2022-05-01 06:52
> Done!

Can you verify that this change only applies to the Fabric version? I’m on a recent (I think) Forge version, and the little guy was raiding pumpkins my root cellar.
