### ISSUE TITLE
Golems Stop Harvesting

### ISSUE THREAD

**Issue by patykin** [t2pellet/strawgolem#127] opened 2022-12-14 20:16 UTC
**Game Info**
Game Version : 1.19
Mod Version : beta.4
Mod Loader : Forge 43.2.0

Golems randomly stop harvesting. There doesn't seem to be a motive to it, sometimes they work, sometimes they stop all together.

**Comment by ejm554** [comment] 2022-12-15 02:40
This sounds similar to #105.

**Comment by t2pellet** [comment] 2022-12-15 13:48
Its worth noting if what we're talking about is just a delay from one harvest to another, there is by design 6-12 seconds between harvests.

@patykin are you observing a long term stoppage of work, or is it just these small delays?

**Comment by patykin** [comment] 2022-12-15 15:06
They work for about 20 minutes and then stop completely, sometimes they stop before that.
I also noted that at times they won't deposit items in the chest if the block above the chest is occupied. 
Note that I'm using infinite health and hunger for test purposes.

**Comment by Miradden** [comment] 2022-12-17 02:17
I also have this problem. A freshly created golem will farm for 1-5 minutes and then stop. They will then either wander around, stand completely still, or stand near/on top of the chest and nod their head up and down. I'm on beta.4 and fabric 0.14.11. Also using infinite health and infinite hunger.

**Comment by Knightjoker101** [comment] 2022-12-23 07:13
I am also having a similar problem. When I spawn in the golems, they just wander around the farm. the farm is fully ready to harvest and there is a chest nearby, but they haven't once farmed the wheat! They continue to just wander around. Please help!

Game Version: 1.18.2
Mod Version: Beta.4
Forge: 40.1.84

**Comment by HipsterGumby** [comment] 2022-12-26 22:00
I'm running into the same problem.

1.19.2 beta.4 but im using Fabric not forge.

They didnt even start harvesting they just walked right past and went to a tree. Not sure if other mods are messing with them but there are lots of ready crops and they wont go near them.

I also have Famer's Delight and Croptopia in my pack.

**Comment by t2pellet** [comment] 2022-12-28 15:22
Question: if you punch one of the idling golems, do they seem to start harvesting?

**Comment by HipsterGumby** [comment] 2022-12-29 06:46
No, punching them doesn't seem to fix it, they just continue to wander.

**Comment by Knightjoker101** [comment] 2022-12-29 06:51
No, punching any of the 9 golems I have make them harvest.The only thing that happens is they loose health, continue to wander in the farm area I have for them and chatter. I have made some in creative as well as survival mod, all on the same world and nothing happens.

**Comment by patykin** [comment] 2022-12-30 04:35
Tested on different worlds creative and survival, no behavior change after damage or if crops states change after they stop working

**Comment by t2pellet** [comment] 2022-12-30 04:41
FYI this has been fixed for the next release

**Comment by Knightjoker101** [comment] 2022-12-30 06:06
Perfect! This seems like an absolute amazing mod! I hope I can get it working in this next update!

**Comment by t2pellet** [comment] 2022-12-30 15:32
New release is out! Should fix the issue

**Comment by dejrons** [comment] 2022-12-30 16:22
I have installed 'strawgolem-1.19.2-2.0.0-beta.5' and when in the previous version they harvested once and then kept wondering around, now they don't harvest crops at all for me ;/
Running 19.2 on Forge

**Comment by ejm554** [comment] 2022-12-30 16:51
> now they don't harvest crops at all for me ;/
> Running 19.2 on Forge

Bummer.

My tests are showing an _improvement!_ My configuration is different, though:

- **Mod file:** strawgolem-1.18.2-2.0.0-beta.5
- **Minecraft version:** 1.18.2
- **Forge version:** 40.1.70

**Comment by t2pellet** [comment] 2022-12-30 18:06
😳 argh back to work again then🫡

**Comment by HipsterGumby** [comment] 2022-12-30 18:28
HUGE improvement from beta.4 but they begin to lose interest again.

I tested it out in my creative world and found that around 8-12 harvests they begin to be disinterested in harvesting. They no longer quickly run to a ready crop. Instead, they only harvest if they find themselves next to a ready crop. When keeping them fenced into a farm they can't go too far and inevitably find themselves in the same square as a ready crop and harvest pretty much instantaneously. If the area is not enclosed, they wander too far and it's rare that they come back in contact with a ready-to-harvest crop. If I push them back to a ready crop, they harvest it immediately and then go back to wandering.

I also found that if I put the chest in the ground (so they can't stand on it and jump over a fence) they get hung up trying to drop the crop off unless I push them.

Also, not sure if it helps but I set my hunger and decay times to "-1'. I don't know if that would affect this issue, but I just wanted to throw it in there.

- **Mod file:** strawgolem-fabric-1.19.2-2.0.0-beta.5
- **Minecraft version:** 1.19.2
- **Fabric Version:** 0.14.11

**Comment by t2pellet** [comment] 2022-12-30 18:54
> I have installed 'strawgolem-1.19.2-2.0.0-beta.5' and in the previous version they harvested once and then kept wondering around, now they don't harvest crops at all for me ;/ Running 19.2 on Forge

Oddly I can't seem to replicate this

**Comment by t2pellet** [comment] 2022-12-30 18:56
> I tested it out in my creative world and found that around 8-12 harvests they begin to be disinterested in harvesting. They no longer quickly run to a ready crop. Instead, they only harvest if they find themselves next to a ready crop. When keeping them fenced into a farm they can't go too far and inevitably find themselves in the same square as a ready crop and harvest pretty much instantaneously. If the area is not enclosed, they wander too far and it's rare that they come back in contact with a ready-to-harvest crop. If I push them back to a ready crop, they harvest it immediately and then go back to wandering. There have been a few times that they will run to a ready crop but then stop, stare at it, and then wander.

a 6-12 second delay between harvests is normal / intended - are you seeing delays outside of that range?

**Comment by HipsterGumby** [comment] 2022-12-30 19:44
> 

Yeah so the 6-12 second delay is present at first. After the 8-12 harvests it could be minutes before.

One odd thing I noticed is if the golem was wandering for minutes on end. I would push them to a crop, they would harvest almost as soon as they touched the block. If they got hung up on dropping off at a chest, after I would push them to fix the hang up, they would immediately go harvest and then go back to wandering for minutes until they came in contact with a ready crop

**Comment by draganczukp** [comment] 2023-04-16 08:57
Any news on this issue? I'm still seeing this behavior where the golem will harvest 2-3 items and just stop completely, and sometimes they don't even start.

**Comment by Kings-Creed** [comment] 2023-05-07 08:53
I did some testing on my own after reading all of these comments

- Golems have trouble differentiating what is on their y-level, it seems the range is set exclusively to x/z. A singular crop anywhere (including glow berries it seems, which means any cave containing this will cause golems to eventually hang) within this x/z range or relatively close will cause the golems to essentially “buffer”, as they become locked onto this specific crop. However, since they cant necessarily go to it due to barriers in the y-direction, the “buffering” occurs
- Proposed change ideas: add a y-level range that golems have to operate within their tether ; alternatively, if item is not picked up within (designated timeframe, preferably something like 1s x tether range) seconds, find other item within range and pick up. This way its guaranteed to at least reset if something goes awry

**Comment by t2pellet** [comment] 2024-07-01 19:34
should be fixed for real this time

**Closed by t2pellet** 2024-07-01 19:34 UTC
Labels: next-release
