### ISSUE TITLE
[1.18.2] Golem stopping work

### ISSUE THREAD

**Issue by siriuslukk** [t2pellet/strawgolem#105] opened 2022-09-10 03:56 UTC
After some time, the golem stops working and starts wander around very slowly shivering making scared sounds.

**Comment by itsdinkd** [comment] 2022-09-30 20:27
![image](https://user-images.githubusercontent.com/35115304/193351160-32752e10-cd02-40a9-b99c-d82107772b15.png)

**Comment by itsdinkd** [comment] 2022-09-30 20:27
like this. they dont pick up or harvest.

**Comment by ejm554** [comment] 2022-11-08 02:17
I noticed the slower working also, at least compared to what I experienced when using the mod in 1.16.5. But it became more concerning when two golems sat down on the ground and began making grunting noises that are typically only made when carrying something heavy. I felt bad! I considered posting a separate issue, but it seems like it could be related to *this* issue.

See screenshot below. [Click here to see a video](https://imgur.com/a/dgSMRVV) from the same scene. (If you want to hear the sound, you may need to unmute it.)

![image of straw golem sitting on ground](https://user-images.githubusercontent.com/26723535/200454406-d6230f15-44a3-4d4b-af15-26dd34d77f4f.png)

**Comment by katubug** [comment] 2022-11-08 02:53
They do sit and pout if they don't get apples within a certain time. It
seems like quite a lot though - every time I went to check on them they
were in pout mode.

**Comment by ejm554** [comment] 2022-11-08 10:29
> They do sit and pout if they don't get apples within a certain time. 

Is it normal for them to make straining noises when they pout?

Come think of it, I recall also seeing golems standing in place while making that sound, as if they were _unable_ to move.

**Comment by ejm554** [comment] 2022-11-21 16:41
> They do sit and pout if they don't get apples within a certain time. It seems like quite a lot though - every time I went to check on them they were in pout mode.

So, I have a new golem, and s/he is making happy sounds and standing. But standing still. They are holding a piece of wheat, close to a chest, but otherwise not moving. (See screenshot.) Eventually, like @katubug mentioned, I can give her/him a little shove, and they go back to work. But it's slow work, and they will again stop a couple blocks short of the chest.

I'm using a this mod in a custom Forge modpack. _**I think it would be interesting to see if this problem exists in an instance where it is the *only* mod. I may test it sometime, but if anyone happens to try before I do, please report your results!**_

![Straw Golem, standing still, holding wheat near a chest, making happy noises](https://user-images.githubusercontent.com/26723535/203109358-8c7d774e-10a7-4b61-a415-10dbab263dda.png)

**Comment by t2pellet** [comment] 2022-12-06 00:35
Their walking speed decreases as they approach the critical point where they sit down and won't do anything.

That said, with the description of the behaviour here, it seems like something isn't working as intended.

Taking a look!

**Comment by ejm554** [comment] 2022-12-06 03:09
When a hungry, pouting golem is fed, should they _stop_ pouting and begin working? I'm used to older versions that didn't require this sort of interaction, so I'm not sure what is normal.

I'm pretty sure I tried feeding mine when they were acting weird, but I could be mistaken. It may be worth testing. 

FYI, below are pics of the same sets of golems that I posted circa November 7 and 21. The images show their health at 2.5 and 4 hearts, respectively. Not sure if these health levels indicate anything about whether they are hungry or should be behaving differently, but I thought I'd pass it along in case it is of use.

Thanks for looking into this, @t2pellet !

![side-by-side images of straw golem characters showing their respective health levels](https://user-images.githubusercontent.com/26723535/205801781-a7e34ce1-112c-4ecf-8758-78216a9ea001.png)

**Comment by t2pellet** [comment] 2022-12-06 11:03
> When a hungry, pouting golem is fed, should they stop pouting and begin working? I'm used to older versions that didn't require this sort of interaction, so I'm not sure what is normal.

Yea, when they're fed they should get back to work.

> Not sure if these health levels indicate anything about whether they are hungry or should be behaving differently, but I thought I'd pass it along in case it is of use.

Hunger is independent of health/lifespan - odd that it isn't showing up in WTHIT though, it should be -- what version of the mod are you using?

For now if you just set hunger to -1 in the config it should just disable the feature. I've also made some changes in master that should help with some of the weird behaviour, will be included in the next release.

**Comment by ejm554** [comment] 2022-12-06 18:32
> odd that it isn't showing up in WTHIT though, it should be -- what version of the mod are you using?

My modpack uses [Jade](https://www.curseforge.com/minecraft/mc-mods/jade) 5.2.4.

**Comment by t2pellet** [comment] 2022-12-07 16:51
Also to clarify regarding the health differences, that's because max health is tied to lifespan

**Comment by t2pellet** [comment] 2022-12-07 17:05
Also -- is there a reason for choosing Jade over WTHIT?

**Comment by katubug** [comment] 2022-12-08 16:52
FWIW I am using The One Probe on Forge, I quite like it.

**Comment by t2pellet** [comment] 2022-12-12 02:25
@ejm554 so in beta.4 it supports Jade on Forge, and there are some logical changes that should eliminate any weirdness related to the hunger mechanic.

marking this issue closed

**Closed by t2pellet** 2022-12-12 02:25 UTC
Labels: next-release

**Comment by ejm554** [comment] 2022-12-15 02:48
So I've been testing 2.0.0 beta.4 in 1.18.2 for Forge, and the little guys are still barely harvesting.

**Comment by t2pellet** [comment] 2022-12-15 13:47
Keeping this issue closed, as this one seemed more tied to confusion/inconsistencies with hunger. theres another issue related to them not harvesting a lot, which I'll keep open.

Its worth noting if what we're talking about is just a delay from one harvest to another, there is by design 6-12 seconds between harvests
