### ISSUE TITLE
Golem move super slow and dont harvest.

### ISSUE THREAD

**Issue by Kindredphoenix** [t2pellet/strawgolem#138] opened 2023-10-24 01:33 UTC
1.19.2 forge version on a server.

I keep having this problem where the golem's just stand there and dont harvest anything, ive configured and increased their range but their at full health and hunger. They just stand there and when they do move their super slow.

**Comment by t2pellet** [comment] 2023-11-05 18:25
duplicate of https://github.com/t2pellet/strawgolem/issues/127

**Closed by t2pellet** 2023-11-05 18:25 UTC
